# Generated by Django 4.0.6 on 2022-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('place', models.CharField(max_length=256, verbose_name='Место')),
            ],
        ),
    ]
