# Generated by Django 4.0.6 on 2022-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='ФОТО'),
            preserve_default=False,
        ),
    ]
